nombre = input("Cual es tu nombre? ")
apellido = input("Cual es tu apellido? ")
rut = input("Cual es tu rut? ")
duoc_email = input("Cual es tu correo del duoc? ")
sede_duoc = input("Cual es tu Sede de Duoc? ")
print("Hola " + nombre, apellido )
print("Tu rut es "+ rut ) 
print("Tu correo de duoc es "+ duoc_email )
print("Tu sede de duoc es."+ sede_duoc) 